# -*- coding: utf-8 -*-
"""LU_decompositions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Du1i1siG4GhjIYuOxAvUJcL36aJzRq64

#**Lab 5 - LU decompositions and Gaussian elimination**

Enter your code in the spaces provided. Do not change any of the variable names or function names that are already provided for you. In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.
"""

# Do not edit this cell.

LabID="Lab5"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

"""**Enter your name, section number, and BYU NetID**"""

# Enter your first and last names in between the quotation marks.

first_name="David"

last_name="Haroldsen"

# Enter your Math 215 section number in between the quotation marks.

section_number="2"

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER!

BYUNetID="davedude"

"""**Import NumPy**"""

import numpy as np

"""**Problem 1**"""

def augment(A,b):
  return np.column_stack((A,b))

"""**Problem 2**"""

def first_column_zeros(A):
  B=np.copy(A)

  nrows = np.shape(A)[0]
  
  I = np.identity(nrows)

  I[:,0] = -B[:,0] * (B[0,0] ** -1)
  I[0,0] = 1 # don't change first row

  return np.matmul(I, B)


"""**Problem 3**"""

def row_echelon(A,b):
  B = augment(A, b)

  nrows = np.shape(A)[0]

  I = np.identity(nrows)

  for c in range(nrows-1):
    op = np.copy(I)

    # Perform the operation needed on the identity matrix
    # For each row below the diagonal, 
    # add the c'th row of B
    # times the negative reciprocal of the diagonal value in B
    # times the value below the diagonal in B, so it always subtracts to 0
    op[c+1:,c] = -B[c+1:,c] * (B[c,c] ** -1)

    B = np.matmul(op, B)

  return B

"""**Problem 4**"""

def LU_decomposition(A):
  U=np.copy(A)
  L=np.identity(len(A))

  m, n = np.shape(A)
  
  for j in range(0, n):
    for i in range(j+1, m):
      L[i,j] = U[i,j] / U[j,j]
      U[i,:] = U[i,:] - L[i,j] * U[j,:]

  return L,U # We've included the return values for you, though your function needs to define them correctly.

"""**Problem 5**"""

def forward_substitution(L,b): # Accepts a lower triangular square matrix L and a vector b, solves Ly=b for y.
  n = len(b)
  y = np.array([0.0]*n)
  for i in range(0, n):
    y[i] = (b[i] - np.dot(y[:i], L[i,:i])) / L[i,i]
  return y

L=np.array([[ 1.0 , 0.0 , 0 ],[ 3.0 , 1.0 , 0.0 ],[-1.1 , 2 , 1 ]])
b=np.array([-2.1 , 1 ,-1 ])
#print(forward_substitution(L,b))

"""**Problem 6**"""

def back_substitution(U,y):    # Accepts an upper triangular square matrix U and a vector b, solves Ux=b for x.
  n = len(y)
  x = np.array([0.0]*n)
  for i in range(n-1, -1, -1):
    x[i] = (y[i] - np.dot(x, U[i,:])) / U[i,i]
  return x

U=np.array([[ 2 ,-3.1 , 1 ],[ 0 , 1 , 3 ],[ 0 , 0 , 4 ]])
y=np.array([ 1 , -2.1 , 3 ])
#print(back_substitution(U,y))

"""**Problem 7**"""

def LU_solver(A,b):
  L,U = LU_decomposition(A)

  y = forward_substitution(L, b)
  x = back_substitution(U, y)

  return x

A=np.array([[ 3 , 1 ,-2 ],[ 1.5 , 2 ,-5 ],[ 2 ,-4 , 1 ]])
b=np.array([ 1.1 , 3 ,-2 ])
#print(LU_solver(A,b))

"""**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file. In the "File" menu select "Download .py". The resulting file can then be uploaded to [gradescope.com](https://gradescope.com) for grading.
"""